package org.gvormbrock.carpark.model;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.hibernate.annotations.ListIndexBase;
import java.util.List;


@Entity
@Table
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Town {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    Country country;

    @ListIndexBase
    @NotNull
    @Size(min = 2, max = 100, message = "Town name must be minimum 2 characters and maximum 100 characters long")
    private String name;

    @NotNull
    @OneToMany(fetch = FetchType.EAGER)
    private List<Url> urls;

    @NotNull
    @OneToMany(fetch = FetchType.EAGER)
    private List<CarPark> carParks;
}