package org.gvormbrock.carpark.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

@Entity
@Table
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Url {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    private Town town;

    @NotNull
    @Size(min = 1, max = 50, message = "title must be minimum 1 characters and maximum 100 characters long")
    private String title;

    @NotNull
    @Size(min = 9, max = 512, message = "urlCarParkCapacity must be minimum 9 characters and maximum 512 characters long")
    private String urlString;
}
